#!/bin/sh

if [ "$EUID" -ne 0 ]
then
    SUDO='sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH -u root'
else
    SUDO=
fi
CPUS=`nproc`

cd /tmp

# pre-create some directories
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Libraries
${SUDO} mkdir -p /usr/GNUstep/Local/Library/Headers

if [ ! -d /tmp/libobjc ]
then
    # pull
    git clone --recursive https://github.com/gnustep/libobjc2.git
    git clone https://github.com/mheily/libpwq.git
    # git clone https://github.com/mheily/libkqueue.git
    git clone https://github.com/nickhutchinson/libdispatch.git
fi

# build and install
echo "======== Installing libobjc2..."
cd /tmp/libobjc2
mkdir build
cd build
cmake -DGNUSTEP_INSTALL_TYPE=LOCAL ../
make -j${CPUS}
${SUDO} -E make install
${SUDO} ldconfig

echo "======== Installing libpwq..."
cd /tmp/libpwq
mkdir build
cd build
cmake ../
make -j${CPUS}
${SUDO} -E make install
${SUDO} ldconfig

# echo "======== Installing libkqueue..."
# cd /tmp/libkqueue
# mkdir build
# cd build
# cmake ../
# make -j${CPUS}
# ${SUDO} -E make install
# ${SUDO} ldconfig

echo "======== Installing libdispatch..."
cd /tmp/libdispatch
rm -rf build
mkdir build
cd build
../configure
make -j${CPUS}
${SUDO} make install
${SUDO} ldconfig


echo "Done."

